URL=https://stag.riggleapp.in/auth
#mobileNumber=8000111199
mobileNumber=8000007880
mobileOtp=




#live Account
#URL=https://app.riggleapp.in/auth
#mobileNumber=8000000041

#mobileNumber=8000007880               #Old